export const API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YzQ3ZWUwYWM4MzU3YTU0NmY0ZTg2NDcyNGI0NGQzNCIsIm5iZiI6MTcyMzMzOTMwNy45MDU1MzMsInN1YiI6IjY2YjgxMWE4N2RmMDM0YjljNDFhMTZlOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Hc4d07rSgmfEbyYOSQn4DDFvYEny_cZSC2zvBjVCnRE";
export const ENDPOINT: "https://api.themoviedb.org/3";
export const ENDPOINT_DISCOVER: string;
export const ENDPOINT_SEARCH: string;
export const ENDPOINT_MOVIE: string;
